services:
  app:
    # build: .
    image: upload-share
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "3000:3000"
    volumes:
      - ./run:/app/run
    environment:
      - UPLOAD_TOKEN=${UPLOAD_TOKEN}
      - ORIGIN=${ORIGIN}
      - MAX_ARCHIVE_SIZE=${MAX_ARCHIVE_SIZE}
      - BODY_SIZE_LIMIT=107374182400 # 100 GB